name: cv804
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - libffi=3.4.4
  # - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.11.11
  # - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - click==8.1.8
      - glfw==2.8.0
      - multipledispatch==1.0.0
      - numpy==1.26.4
      - opencv-python==4.10.0.84
      - pyopengl==3.1.7
      - pyopengl-accelerate==3.1.7
      - pyrr==0.10.3
